import fs from 'node:fs';
import path from 'node:path';
import mongoose from 'mongoose';
import { env } from '../config/env.js';
import { buildSitemapXmlString } from '../utils/sitemap.js';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..',
);

/**
 * Same flow as robots.txt: written under client/public/, copied to dist by Vite.
 * Gitignored — generated by `npm run build:sitemap` or root `npm run build`.
 */
export const clientSitemapPath = path.join(
  repoRoot,
  'client',
  'public',
  'sitemap.xml',
);

async function main() {
  console.log('buildSitemap: connecting to MongoDB...');
  await mongoose.connect(env.MONGODB_URI);
  const siteBase = env.PUBLIC_SITE_URL.trim() || env.CLIENT_URL;
  const xml = await buildSitemapXmlString(siteBase);
  fs.mkdirSync(path.dirname(clientSitemapPath), { recursive: true });
  fs.writeFileSync(clientSitemapPath, xml, 'utf8');
  console.log(`buildSitemap: wrote ${clientSitemapPath}`);
  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
